script:
  - git clone https://github.com/servo/servo
  - cd servo
  - GIT_PAGER= git log -n 1
  - git ls-remote https://github.com/rust-lang/rust master | cut -f1 > rust-commit-hash
  - ./mach bootstrap
  - ./mach rustc --version -v
  - ./mach cargo --version -v
  - ./mach cargo check

  # Tests seem to be failing (and taking too much time)
  # https://travis-ci.org/servo/servo-with-rust-nightly/builds/194321428
#  - ./mach build --dev
#  - ./mach test-compiletest
#  - ./mach test-unit

dist: trusty
sudo: 9000
addons:
  apt:
    packages:
      - cmake
      - freeglut3-dev
      - gperf
      - libosmesa6-dev
      - libgles2-mesa-dev
      - python-virtualenv
      - xorg-dev
      - ccache
      - libdbus-glib-1-dev
      - libavformat-dev
      - libavcodec-dev
      - libavutil-dev
      - libedit-dev
cache:
  directories:
    - $HOME/.cargo
    - $HOME/.ccache
env: CCACHE=/usr/bin/ccache
notifications:
  email: false
  irc:
    channels: "irc.mozilla.org#servo"
    on_success: never
    on_failure: always
    template: "Servo failed to build with Rust nightly: %{build_url} CC nox, SimonSapin"
